export const url = [
  "Aceh",
  "Sumatera Utara",
  "Sumatera Barat",
  "Riau",
  "Jambi",
  "Sumatera Selatan",
  "Bengkulu",
  "Lampung",
  "Kepulauan Bangka Belitung",
  "Kepulauan Riau",
  "Jakarta",
  "Jawa Barat",
  "Jawa Tengah",
  "Yogyakarta",
  "Jawa Timur",
  "Banten",
  "Bali",
  "Nusa Tenggara Barat",
  "Nusa Tenggara Timur",
  "Kalimantan Barat",
  "Kalimantan Tengah",
  "Kalimantan Selatan",
  "Kalimantan Timur",
  "Kalimantan Utara",
  "Sulawesi Utara",
  "Sulawesi Tengah",
  "Sulawesi Selatan",
  "Sulawesi Tenggara",
  "Gorontalo",
  "Sulawesi Barat",
  "Maluku",
  "Maluku Utara",
  "Papua Barat",
  "Papua",
  "Papua Barat Daya",
  "Papua Pegunungan",
  "Papua Tengah",
  "Papua Selatan",
];

export const countUrl = {
  data: `
        Aceh,
        Sumatera Utara,
        Sumatera Barat,
        Riau,
        Jambi,
        Sumatera Selatan,
        Bengkulu,
        Lampung,
        Kepulauan Bangka Belitung,
        Kepulauan Riau,
        Jakarta,
        Jawa Barat,
        Jawa Tengah,
        Yogyakarta,
        Jawa Timur,
        Banten,
        Bali,
        Nusa Tenggara Barat,
        Nusa Tenggara Timur,
        Kalimantan Barat,
        Kalimantan Tengah,
        Kalimantan Selatan,
        Kalimantan Timur,
        Kalimantan Utara,
        Sulawesi Utara,
        Sulawesi Tengah,
        Sulawesi Selatan,
        Sulawesi Tenggara,
        Gorontalo,
        Sulawesi Barat,
        Maluku,
        Maluku Utara,
        Papua Barat,
        Papua,
        Papua Barat Daya,
        Papua Pegunungan,
        Papua Tengah,
        Papua Selatan
    `,
};

export const produce = [
  "Bawang Merah",
  "Bawang Putih",
  "Jagung",
  "Cabai Rawit",
  "Cabai Merah",
  "Beras Premium",
  "Beras Medium",
  "Beras SPHP",
];
